name: TestPlugin
version: '1.0'
main: com.ryderbelserion.stick.paper.plugin.TestPlugin
description: Paper Test Plugin
api-version: '1.19'

bootstrapper: com.ryderbelserion.stick.paper.plugin.CrazyStarter