[versions]

github = "https://github.com/Crazy-Crew/CrazyCore"
beta = "false"

[plugins]

minotaur = { id = "com.modrinth.minotaur", version = "2.8.0" }
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.1.0" }