name: CrazyExample
main: us.crazycrew.example.CrazyExample

version: ${version}
api-version: '1.19'
description: ${description}

bootstrapper: us.crazycrew.example.CrazyLoader
#loader: us.crazycrew.example.CrazyExample